" don't need to be compatible with old vi
" not on my default when executing my vimrc, but helps when someone wants
" to use my vimrc at the command line with the -u flag
set nocompatible

" Vim Plug - vim plugin manager: https://github.com/junegunn/vim-plug
" install if necessary
if empty(glob('~/.config/nvim/autoload/plug.vim'))
    " vim plug package installation
    silent !curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    " set up augroup to run installation command, resource and then we won't
    " hit this case next time
    augroup InstallingPlugs
        autocmd!
        autocmd VimEnter * PlugInstall | source $MYVIMRC
    augroup END
endif

" best leader. set immediately so all mappings adopt it
let mapleader = "\<Space>"

" Start plugin manager, specify directory for plugin files
call plug#begin('~/.config/nvim/plugged')

" ncm2 and other python plugins require python and the pynvim package
" This is installed via pyenv in a virtualenv
" Installtion instructions in https://github.com/deoplete-plugins/deoplete-jedi/wiki/Setting-up-Python-for-Neovim
let g:python3_host_prog = '/Users/williamdeuschle/.pyenv/versions/neovim/bin/python'

" Plugins section
""""""""""""""""
" Autocomplete "
""""""""""""""""
Plug 'ncm2/ncm2' " https://github.com/ncm2/ncm2, autocompletion plugin
Plug 'roxma/nvim-yarp' " remote plugin manager, doesn't use :UpdateRemotePlugin
" enable ncm2 for all buffers (if it's been loaded)
if !empty(glob('~/.config/nvim/plugged/ncm2/'))
    autocmd BufEnter * call ncm2#enable_for_buffer()
endif
" important: :help Ncm2PopupOpen, :help completeopt for more information
" in order: don't insert match until selected, pop a menu even when only one
" option, don't select a match - force the user to select it from the menu
set completeopt=noinsert,menuone,noselect
" note: you need to install completion sources to get completions. Check
" our wiki page for a list of sources: https://github.com/ncm2/ncm2/wiki
" thesre are the completion sources to get completions
Plug 'ncm2/ncm2-bufword'
Plug 'ncm2/ncm2-tmux'
Plug 'ncm2/ncm2-path'
" scroll from top to bottom when tabbing by default
inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"

""""""""""""""
" Commenting "
""""""""""""""
Plug 'scrooloose/nerdcommenter'

""""""""""""""""
" File Finding "
""""""""""""""""
Plug 'scrooloose/nerdtree'
" mapping to open NERDTree
noremap <Leader>f :NERDTreeToggle<CR>

"""""""""""""""""""""""
" Syntax Highlighting "
"""""""""""""""""""""""
" Async highlighting
Plug 'neomake/neomake'

"""""""""""
" Styling "
"""""""""""
" Monokai
Plug 'sickill/vim-monokai'
" Lightline - for pretty statusline and tmuxline
Plug 'itchyny/lightline.vim'
" for list of buffers
Plug 'bling/vim-bufferline'
" Git plugin, used to show git branch in lightline
Plug 'tpope/vim-fugitive'
" Tmuxline, used with lightline styles
Plug 'edkolev/tmuxline.vim'
" dont use the powerline separators
let g:tmuxline_powerline_separators = 0

""""""""""""""""""""
" Language Styling "
""""""""""""""""""""

" Markdown styling
Plug 'plasticboy/vim-markdown'
" Python indenting
Plug 'Vimjas/vim-python-pep8-indent'

""""""""""""""""""""
" Navigation Tools "
""""""""""""""""""""

" fzf for file finding, need both plugins
" install --bin because we only use this in vim
Plug 'junegunn/fzf', { 'dir': '~/.config/nvim/.fzf', 'do': './install --bin' }
Plug 'junegunn/fzf.vim'
" Modifications for FZF "
" git files
nnoremap <silent> <C-p> :GitFiles<CR>
" file history
nnoremap <silent> <leader>h :History<CR>
" tags in the project (need to be generated)
nnoremap <silent> <leader>t :Tags<CR>
" tags in the current buffer
nnoremap <silent> <leader>b :BTags<CR>


" initialize plugin system
call plug#end()


"""""""""""""""""""""""
" General Preferences "
"""""""""""""""""""""""

" Colors
syntax enable
if !empty(glob('~/.config/nvim/plugged/vim-monokai/colors/monokai.vim'))
    colorscheme monokai
else
    colorscheme default
endif


" Formatting
set fileformat=unix " Make sure the files are always unix
set fileformats=unix " Make sure the files are always unix
set tabstop=4 " number of visual spaces per TAB
set softtabstop=4 " number of spaces in tab when editing
set shiftwidth=4 " number of spaces inserted for indendation
set expandtab " tabs are spaces (tab button = spaces)
set colorcolumn=80 " keep within this column

" UI stuff
set number " show line nums
set showcmd " show last entered command
set cursorline " highlight current line
filetype indent on " load filetype-specific indent files
set wildmenu " visual autocomplete for command menu
set lazyredraw " redraw only when we need to.
set showmatch " show matching ()
set mouse=a " Turn on mouse mode

" keyboard stuff
" No cheating!
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>
inoremap jj <ESC> " helps speed up normal mode
set scrolloff=5 " moves file up and down with buffer of 5 lines for cursor

" search stuff
set incsearch " search as characters are entered
set hlsearch " highlight matches
set ignorecase " ignore case if all lowercase search string
set smartcase " don't ignore case if we put a capital letter in search string

" incremental substitution when changing text with %s, you see it in a split
set inccommand=split

" write hotkey
nnoremap <Leader>w :w<CR>

"""""""""""""""""""""""
" Copying and pasting "
"""""""""""""""""""""""

" copy last yanked text to system clipboard
nnoremap <Leader>m :let @+=@"<CR>

" copy current file path to system clipboard
nnoremap <Leader>p :let @+=@%<CR>

" Reselecting pasted/yanked text
nnoremap <expr> gp '`[' . strpart(getregtype(), 0, 1) . '`]'

" paste last yank (in case we overwrite "" buffer with a delete)
nnoremap <Leader>y "0p

" Paste mode toggle - disable auto indenting, etc.
set pastetoggle=<F2>

" Finding the current absolute file path
nnoremap <Leader>g 1<C-g>

"""""""""""""""""""""""
" Syntax Highlighting "
"""""""""""""""""""""""
" Python
let g:neomake_python_enabled_makers = ['flake8']
" Ignore no blank line at end of file error
let g:neomake_python_flake8_args = ['--ignore=W391']

" Neomake
augroup RunNeomake
    autocmd!
    autocmd BufWritePost * Neomake
augroup END

"""""""""""""
" Lightline "
"""""""""""""

" don't let bufferline echo to the commmand bar
let g:bufferline_echo=0
" always display the status line in vim
set laststatus=2
" always display the tabline in vim
set showtabline=2
" no need for the mode (insert, normal, etc.) because shown in lightline
set noshowmode
" Explaining our lightline settings here
"   colorscheme: wombat is preferred
"   active: configure bottom left of statusline
"   component_function - gitbranch: show git branch in statusline
"   tabline: show bufferline at top left of screen
"   component_expand - bufferline: show buffers, an expanding component
"   component_type - bufferline: color the bufferline (current buffer dark)
let g:lightline = {
      \ 'colorscheme': 'wombat',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
      \ },
	  \ 'component_function': {
      \   'gitbranch': 'fugitive#head'
      \ },
      \ 'tabline': {
      \   'left': [ ['bufferline'] ]
      \ },
      \ 'component_expand': {
      \   'bufferline': 'LightlineBufferline',
      \ },
      \ 'component_type': {
      \   'bufferline': 'tabsel',
      \ },
      \ }

" function that generates the buffer list to be placed in the tabline
function! LightlineBufferline()
  " refresh the current state of the buffers
  call bufferline#refresh_status()
  " return a [left, current, right] list of buffers
  return [ g:bufferline_status_info.before, g:bufferline_status_info.current, g:bufferline_status_info.after]
endfunction

"""""""""""""""""""""
" Buffer Management "
"""""""""""""""""""""

" for editing files in buffers (switch between them without having saved)
set hid
" To open a new empty buffer
" This replaces :tabnew which I used to bind to this mapping
nmap <leader>T :enew<cr>
" Move to the next buffer
nmap <leader>l :bnext<CR>
" Move to the previous buffer
nmap <leader>k :bprevious<CR>
" Close the current buffer and move to the previous one
" This replicates the idea of closing a tab
nmap <leader>q :bp <BAR> bd #<CR>
" Show all open buffers and their status
nmap <leader>bl :ls<CR>

""""""""
" Misc "
""""""""
" auto cmd to strip whitespace
" first create the function
function! s:StripTrailingWhitespaces()
    " Prep- save last search and cursor position.
    let _s=@/
    let l = line(".")
    let c = col(".")
    " Do the business:
    %s/\s\+$//e
    " Clean up: restore previous search history, and cursor position
    let @/=_s
    call cursor(l, c)
endfunction
" then create the command group
augroup StripWhiteSpace
    autocmd!
    autocmd BufWritePre :call s:StripTrailingWhitespaces()
augroup END
